version: "3.6"
 
services:
  site-db:
    image: mysql:5.7
    restart: always
    container_name: 0xffff-mysql
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - ./data/db-data:/var/lib/mysql
      - ./services/mysql/ngram.cnf:/etc/mysql/conf.d/ngram.cnf

  nginx:
    image: 0xffff-nginx:latest
    build: ./services/nginx
    container_name: 0xffff-nginx
    restart: always
    depends_on:
      - site-fpm
    ports:
      - ${NGINX_HTTP_PORT:-8080}:80
      - ${NGINX_HTTPS_PORT:-8443}:443
    volumes:
      - ./logs:/var/log/nginx
      - ./services/nginx/nginx-conf/docker-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/nginx-conf/snippets:/etc/nginx/snippets:ro
      - ./data/app/assets:/wwwroot/public/assets:ro
      - ./public:/wwwroot/public:ro
    environment:
      TZ: 'Asia/Shanghai'
    extra_hosts:
      - "localhost:127.0.0.1"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy off http://localhost/get-health || exit 1"]
      interval: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  site-fpm:
    image: 0xffff-flarum:latest
    build: ./services/php-fpm 
    container_name: 0xffff-php-fpm
    depends_on:
      - redis
      - site-db
    restart: always
    expose:
      - 9000
    volumes:
      - ./logs:/var/log
      - ./:/wwwroot
      - ./data/.empty:/wwwroot/data
      - ./data/.empty:/wwwroot/logs
      - ./data/app/storage:/wwwroot/storage
      - ./data/app/assets:/wwwroot/public/assets
      # - ./data/app/config.php:/wwwroot/config.php
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm"]
      interval: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  # https://laravel-news.com/laravel-scheduler-queue-docker
  scheduler:
    image: 0xffff-flarum:latest
    container_name: 0xffff-scheduler
    depends_on:
      - site-fpm
    restart: always
    volumes:
      - ./logs:/var/log
      - ./:/wwwroot
      - ./data/.empty:/wwwroot/data
      - ./data/.empty:/wwwroot/logs
      - ./data/app/storage:/wwwroot/storage
      - ./data/app/assets:/wwwroot/public/assets
      # - ./data/app/config.php:/wwwroot/config.php
    environment:
      CONTAINER_ROLE: scheduler

  # queue worker
  queue_worker:
    image: 0xffff-flarum:latest
    container_name: 0xffff-queue-worker
    depends_on:
      - site-fpm
    restart: always
    volumes:
      - ./logs:/var/log
      - ./:/wwwroot
      - ./data/.empty:/wwwroot/data
      - ./data/.empty:/wwwroot/logs
      - ./data/app/storage:/wwwroot/storage
      - ./data/app/assets:/wwwroot/public/assets
      # - ./data/app/config.php:/wwwroot/config.php
    environment:
      CONTAINER_ROLE: queue

  # redis for queue and session
  redis:
    image: redis:6.2.5
    container_name: 0xffff-redis
    volumes:
      - ./data/redis-data:/data
    restart: always
    expose:
      - 6379

  sonic:
    image: valeriansaliou/sonic:v1.3.0
    container_name: 0xffff-sonic
    volumes:
      - ./data/sonic-store:/var/lib/sonic/store
      - ./services/sonic/config.cfg:/etc/sonic.cfg
    restart: always
    expose:
      - 1491
