version: '3.8'

services:
  app:
    image: ghcr.io/0xffff-one/flarum-0x-devcontainer:latest

    volumes:
      - ../..:/workspaces:cached
      - app-data:/data
      - home:/home

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./mysql/ngram.cnf:/etc/mysql/conf.d/ngram.cnf
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: flarum
      MYSQL_DATABASE: flarum
      MYSQL_USER: flarum
      MYSQL_PASSWORD: flarum

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: flarum
      UPLOAD_LIMIT: 300M

volumes:
  mysql-data:
  app-data:
  home:
